//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpopZtation
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayTransaction
    {
        public int TransactionID { get; set; }
        public string TransactionDate { get; set; }
        public string CustomerName { get; set; }
        public string AlbumName { get; set; }
        public string AlbumImage { get; set; }
        public Nullable<int> AlbumPrice { get; set; }
        public int Qty { get; set; }
    }
}
